directories:
  output: dist-mac
  buildResources: build
appId: com.translator.app
productName: 文本翻译工具
win:
  target: nsis
  icon: build/icon.ico
  signAndEditExecutable: false
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: 文本翻译工具
files:
  - filter:
      - src/**/*
      - package.json
mac:
  category: public.app-category.utilities
  target:
    - dmg
    - zip
  icon: build/icon.icns
  darkModeSupport: true
dmg:
  title: 文本翻译工具
  icon: build/icon.icns
  contents:
    - x: 130
      'y': 220
    - x: 410
      'y': 220
      type: link
      path: /Applications
electronVersion: 34.3.0
